/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "eu-west-2",
    "aws_cognito_identity_pool_id": "eu-west-2:ec87757a-7209-4e3e-9e9e-d9591d7a2124",
    "aws_cognito_region": "eu-west-2",
    "aws_user_pools_id": "eu-west-2_VcNMUpdU9",
    "aws_user_pools_web_client_id": "1003msitpof8t9ngrccm135mn3",
    "oauth": {
        "domain": "amplifyappreactampli8124214a-8124214a-staging.auth.eu-west-2.amazoncognito.com",
        "scope": [
            "phone",
            "email",
            "openid",
            "profile",
            "aws.cognito.signin.user.admin"
        ],
        "redirectSignIn": "http://localhost:3000/,https://amplifyappreactampli8124214a-8124214a/",
        "redirectSignOut": "http://localhost:3000/,https://amplifyappreactampli8124214a-8124214a/",
        "responseType": "code"
    },
    "federationTarget": "COGNITO_USER_POOLS",
    "aws_cognito_username_attributes": [],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ]
};


export default awsmobile;
